# Generated by Django 3.2.4 on 2021-06-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=None, max_length=56),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=None, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='postalcode',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
