# Generated by Django 3.2.4 on 2021-06-04 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0002_auto_20210604_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
