# Generated by Django 3.2.4 on 2021-06-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0004_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(default=0, max_length=56),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0, max_length=32),
        ),
    ]
