# Generated by Django 3.2.4 on 2021-06-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0006_auto_20210604_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postalcode',
        ),
    ]
