# Generated by Django 3.2.4 on 2021-06-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0007_auto_20210604_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
