# Generated by Django 3.2.4 on 2021-06-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0008_auto_20210604_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.IntegerField(default=0, max_length=265),
        ),
        migrations.AddField(
            model_name='user',
            name='currency',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=0, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.TextField(default=0, max_length=56),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.IntegerField(default=0, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='postalcode',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
