# Generated by Django 3.2.4 on 2021-06-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userwallet', '0011_remove_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
